services:
  db:
    image: postgres:15-alpine
    container_name: cafeteria_db_cont
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}       
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/reports_vw.sql:/docker-entrypoint-initdb.d/2-reports_vw.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/3-seed.sql
      - ./db/roles.sql:/docker-entrypoint-initdb.d/4-roles.sql

  backend:
    build: ./backend
    container_name: cafeteria_backend_cont
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - PORT=4000
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  app:
    build: .
    container_name: cafeteria_app_cont
    ports:
      - "3005:3000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - db
      - backend